import Option from "../model/search/Option";

const cities: Option[] = [
  {
    label: "Tokyo",
  },
  { label: "Paris" },
  { label: "Wien" },
  { label: "Frankfurt" },
  { label: "Minhen" },
  { label: "Linz" },
  { label: "Madrid" },
  { label: "Barcelona" },
  { label: "Nis" },
  { label: "Amsterdam" },
  { label: "Rotrdam" },
  { label: "Kiev" },
  { label: "Antalya" },
  { label: "Ankara" },
  { label: "Istanbul" },
  { label: "Moscow" },
  { label: "Zagreb" },
  { label: "Budapest" },
  { label: "Manila" },
  { label: "Jakarta" },
  { label: "Delhi" },
  { label: "Belgrade" },
  { label: "Mumbai" },
  { label: "Mexico City" },
  {
    label: "London",
  },
  { label: "New York" },
  { label: "Dhaka" },
  { label: "Washington" },
  { label: "New Jersey" },
  { label: "Buenos Aires" },
  { label: "Rio" },
  { label: "Lisabon" },
  { label: "Bukurest" },
  { label: "Bejiing" },
  { label: "Dublin" },
];

export default cities;
